@HostAddress = http://localhost:5080

### HTTP 400: The schoolclass field is required.
GET {{HostAddress}}/api/registrations
Accept: application/json

### HTTP 200 OK
GET {{HostAddress}}/api/registrations?schoolclass=4AHIF
Accept: application/json

### HTTP 200 OK: leeres Array
GET {{HostAddress}}/api/registrations?schoolclass=6AAIF
Accept: application/json

### HTTP 200 OK
GET {{HostAddress}}/api/registrations/1
Accept: application/json

### HTTP 404: Registration with ID 999 not found.
GET {{HostAddress}}/api/registrations/999
Accept: application/json

### HTTP 201 Created
POST {{HostAddress}}/api/registrations
Content-Type: application/json

{
  "languageweekId": 4,
  "studentId": 10,
  "registerDate": "2036-03-20T10:00:00Z"
}

### HTTP 400: Languageweek id not found
POST {{HostAddress}}/api/registrations
Content-Type: application/json

{
  "languageweekId": 999,
  "studentId": 10,
  "registerDate": "2026-03-20T10:00:00Z"
}

### HTTP 400: Student id not found.
POST {{HostAddress}}/api/registrations
Content-Type: application/json

{
  "languageweekId": 4,
  "studentId": 999,
  "registerDate": "2026-03-20T10:00:00Z"
}

### HTTP 400: Registration date is in the past.
POST {{HostAddress}}/api/registrations
Content-Type: application/json

{
  "languageweekId": 4,
  "studentId": 10,
  "registerDate": "2026-01-20T10:00:00Z"
}

### DELETE eine Registrierung (Erfolgsfall: Id 2 existiert im Seed)
DELETE {{HostAddress}}/api/registrations/2

### HTTP 404: Registration id not found.
DELETE {{HostAddress}}/api/registrations/999
